version: '3.8'

x-cache-from:
  - &app-cache-from
    cache_from:
      - php:8.0-fpm

services:
  db-test-unitaire:
    image: postgres:13-alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db-test-unitaire
        POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  php-test-unitaire:
    image: php:8.0-fpm
    build:
      context: ./docker/php-fpm
      <<: *app-cache-from
    depends_on:
      - db-test-unitaire
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - ./:/var/www
      - app-cache:/var/www/var

  nginx-test-unitaire:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-test-unitaire
    ports:
      - "80:80"
      - "443:443"

volumes:
  db-data: {}
  app-cache: {}
